# version: "3.8"
services:
  backend:
    container_name: bank-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=mini_bank
      - DATABASE_URL=postgresql://postgres:password@postgres-db:5432/mini_bank
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - NODE_ENV=production
      - PORT=3001
    depends_on:
      - postgres-db
    restart: always
    networks:
      - mini-bank-network

  postgres-db:
    container_name: postgres-db
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mini_bank
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - mini-bank-network

volumes:
  postgres-data:
    driver: local

networks:
  mini-bank-network:
    driver: bridge
