# version: '3.8'
services:
  backend:
    container_name: mini-bank-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres-db
    restart: always
    networks:
      - mini-bank-network

  postgres-db:
    container_name: mini-bank-postgres-db
    image: postgres:latest
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mini-bank-network

volumes:
  postgres-data:
    driver: local

networks:
  mini-bank-network:
    driver: bridge
